services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    network_mode: host
  uml:
    image: plantuml/plantuml-server
    restart: always
    ports:
      - "9999:8080"
